---
- name: playing with facts
  hosts: localhost
  gather_facts: true

  tasks:
  - debug: 
      var: ansible_facts 

  - debug:
      msg: 
        - " Data type of 'ansible_hostname'  is {{ ansible_hostname | type_debug }} "
        - " Data type of 'ansible_selinux' is {{ ansible_selinux | type_debug }} "
        - " Data type of 'ansible_all_ipv4_addresses' is {{ ansible_all_ipv4_addresses | type_debug }} "

  - debug: 
      msg: "Host {{ ansible_hostname }} Linux distribution is {{ ansible_distribution }}"

  - debug:
      msg: "{{ ansible_all_ipv4_addresses }}"

